port: 8080
debug: false
crypto:
  private_key_path: "/app/test/key_pair/demo.rsa"
  public_key_path: "/app/test/key_pair/demo.rsa.pub"
frontend:
  path: "/app/web"
  index: "index.html"
logger:
  path: ""
  level: "info"
http:
  read_buffer_size: 16384
  write_buffer_size: 16384
  read_timeout: 18
  write_timeout: 18
  idle_timeout: 60
  request_timeout: 5
mysql:
  dsn: ""
  max_lifetime: 20
  max_open_conns: 100
  max_idle_conns: 100
cookie:
  cookie_name: "SSO_C"
  cookie_domain: "localhost"
  cookie_valid_hours: 20
smtp:
  smtp_user: ""
  smtp_password: ""
  smtp_host: ""
  smtp_port: 465
  smtp_ssl: true
