port: 8080
private_key_path: "./test/key_pair/demo.rsa"
public_key_path: "./test/key_pair/demo.rsa.pub"
debug: false
frontend:
  path: "/app/web"
  index: "index.html"
logger:
  path: ""
  level: ""
http:
  read_buffer_size: 16384
  write_buffer_size: 16384
  read_timeout: 18
  write_timeout: 18
  idle_timeout: 60
  request_timeout: 5
mysql:
  dsn: "sso:sso@tcp(127.0.0.1:3306)/sso?charset=utf8"
  max_lifetime: 20
  max_open_conns: 100
  max_idle_conns: 100
cookie:
  cookie_name: "SSO_C"
  cookie_domain: "localhost"
  cookie_valid_hours: 20
